import "babel-polyfill";
import riot from "riot";
global.riot = riot;
import "ctx-core/dom/ctx.tag";
import "pioneer/spt-pioneer.tag";
import "pioneer/spt-pioneer-layout.tag";
import "pioneer/spt-pioneer-dialog.tag";
import "ctx-core/dialog/ctx-dialog.tag";
import "ctx-core/dialog/ctx-dialog-topbar.tag";
import "ctx-core/dialog/ctx-dialog-position-right.tag";
import "pioneer/spt-pioneer-menu-dialog.tag";
import "banner/spt-banner.tag";
import "pioneer/spt-pioneer-banner.tag";
import "pioneer/bernie-pioneer-root.tag";
import "site/spt-twitter.tag";
import "vote-where/vote-where.webpack";
import "voting-issue/voting-issue.webpack";