import "babel-polyfill";
import riot from "riot";
global.riot = riot;
import "ctx-core/dom/ctx.tag";
import "ctx-core/dialog/ctx-dialog.tag";
import "ctx-core/dialog/ctx-dialog-topbar.tag";
import "ctx-core/dialog/ctx-dialog-position-center.tag";
import "site/spt-about-us.tag";
import "site/spt-twitter.tag";
import "splash/spt-splash.tag";
import "splash/spt-splash-root.tag";
import "splash/spt-splash-dialog.tag";
import "banner/spt-banner.tag";
import "splash/spt-splash-banner.tag";
import "early-voting/spt-early-voting-dialog.tag";
import "early-voting-issue/spt-early-voting-issue-dialog.tag";
import "addtocalendar/spt-addtocalendar-dialog.tag";
import "check-registration/spt-check-registration-dialog.tag";